; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:stable]
#aus wled#platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2.3/platform-espressif32-2.0.2.3.zip
#aus wledplatform = espressif32@3.5.0

#von mir platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

platform = espressif32   
framework = arduino
board = esp32dev

monitor_speed = 115200       
lib_deps =  
            ../settings
            ../libs/ethernetmqtt
 #           ../libs/w5100ethernetmqtt     #im aktuellen ESPFramework ist ein Bug, warten bis der raus ist 07.01.2025
            ../libs/espwifimqtt
            ../libs/serialdummymqtt
            ../libs/myInputsOutputs
            ../libs/arduinowatchdog
            ../libs/myInputsOutputs
            ../libs/myEncoderESP
            ../libs/myotaupdater
            ../libs/myupdatewuenscher
            ../libs/myRGBW
            ../libs/ir
            ../libs/mySpiffsSettingsloader 
            ../libs/myDMXDimmerESP
            ../libs/hilfe
            ../libs/canhardESP
            ../libs/myCAN
            
