; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200    

 
board_build.filesystem = spiffs
#upload_protocol = espota
#upload_port = 192.168.1.141    ; IP deines ESP32h


build_flags =
     -D USER_SETUP_LOADED=1
     -include $PROJECT_DIR/lib/myTFTSettings/src/User_Setup_tft.h

   

lib_deps =  
            ../libs/SmartHomeSettings
            ../libs/espwifimqtt
            ../libs/ethernetmqtt
            ../libs/serialdummymqtt
            ../libs/myInputsOutputs
            ../libs/arduinowatchdog
            ../libs/mybeeper
            ../libs/mydisplay
            ../libs/mydisplayHeizungsteil
            ../libs/myEncoderESP
            ../libs/myhdc108
            ../libs/myheiztemp
            ../libs/myUhrESP
            ../libs/myUhrBasis
            ../libs/myotaupdater
            ../libs/myhelligkeit
            ../libs/myRGBW
            ../libs/ir
            ../libs/geaendertesAdafruit_MCP2515  #brauche ich nur zum übersetzen,.... wird hier nicht im code verwendet
            ../libs/hilfe
            ../libs/canhardESP
            ../libs/myCAN
            
